<?php
/** A simple text block **/
class Four_Block extends Block {
    //set and create block
    function __construct() {
        $block_options = array(
            'name'=> __('Hover block', 'oblivion'),
            'size'=> 'span3',
        );
        //create the block
        parent::__construct('four_block', $block_options);
    }
    function form($instance) {
        $defaults = array(
            'text'=> '',
            'icon'=> 'none',
            'title' => 'none',
        );
        $icon_options = array(
            'none'=> 'None',
            'adjust' => 'adjust',
			'adn' => 'adn',
			'align-center' => 'align center',
			'align-justify' => 'align justify',
			'align-left' => 'align left',
			'align-right' => 'align right',
			'ambulance' => 'ambulance',
			'anchor' => 'anchor',
			'android' => 'android',
			'angellist' => 'angellist',
			'angle-double-down' => 'angle double down',
			'angle-double-left' => 'angle double left',
			'angle-double-right' => 'angle double right',
			'angle-double-up' => 'angle double up',
			'angle-down' => 'angle down',
			'angle-left' => 'angle left',
			'angle-right' => 'angle right',
			'angle-up' => 'angle up',
			'apple' => 'apple',
			'archive' => 'archive',
			'area-chart' => 'area chart',
			'arrow-circle-down' => 'arrow circle down',
			'arrow-circle-left' => 'arrow circle left',
			'arrow-circle-o-down' => 'arrow circle o down',
			'arrow-circle-o-left' => 'arrow circle o left',
			'arrow-circle-o-right' => 'arrow circle o right',
			'arrow-circle-o-up' => 'arrow circle o up',
			'arrow-circle-right' => 'arrow circle right',
			'arrow-circle-up' => 'arrow circle up',
			'arrow-down' => 'arrow down',
			'arrow-left' => 'arrow left',
			'arrow-right' => 'arrow right',
			'arrow-up' => 'arrow up',
			'arrows' => 'arrows',
			'arrows-alt' => 'arrows alt',
			'arrows-h' => 'arrows h',
			'arrows-v' => 'arrows v',
			'asterisk' => 'asterisk',
			'at' => 'at',
			'backward' => 'backward',
			'ban' => 'ban',
			'bar-chart' => 'bar chart',
			'barcode' => 'barcode',
			'bars' => 'bars',
			'bed' => 'bed',
			'beer' => 'beer',
			'behance' => 'behance',
			'behance-square' => 'behance square',
			'bell' => 'bell',
			'bell-o' => 'bell o',
			'bell-slash' => 'bell slash',
			'bell-slash-o' => 'bell slash o',
			'bicycle' => 'bicycle',
			'binoculars' => 'binoculars',
			'birthday-cake' => 'birthday cake',
			'bitbucket' => 'bitbucket',
			'bitbucket-square' => 'bitbucket square',
			'bold' => 'bold',
			'bolt' => 'bolt',
			'bomb' => 'bomb',
			'book' => 'book',
			'bookmark' => 'bookmark',
			'bookmark-o' => 'bookmark o',
			'briefcase' => 'briefcase',
			'btc' => 'btc',
			'bug' => 'bug',
			'building' => 'building',
			'building-o' => 'building o',
			'bullhorn' => 'bullhorn',
			'bullseye' => 'bullseye',
			'bus' => 'bus',
			'buysellads' => 'buysellads',
			'calculator' => 'calculator',
			'calendar' => 'calendar',
			'calendar-o' => 'calendar o',
			'camera' => 'camera',
			'camera-retro' => 'camera retro',
			'car' => 'car',
			'caret-down' => 'caret down',
			'caret-left' => 'caret left',
			'caret-right' => 'caret right',
			'caret-square-o-down' => 'caret square o down',
			'caret-square-o-left' => 'caret square o left',
			'caret-square-o-right' => 'caret square o right',
			'caret-square-o-up' => 'caret square o up',
			'caret-up' => 'caret up',
			'cart-arrow-down' => 'cart arrow down',
			'cart-plus' => 'cart plus',
			'cc' => 'cc',
			'cc-amex' => 'cc amex',
			'cc-discover' => 'cc discover',
			'cc-mastercard' => 'cc mastercard',
			'cc-paypal' => 'cc paypal',
			'cc-stripe' => 'cc stripe',
			'cc-visa' => 'cc visa',
			'certificate' => 'certificate',
			'chain-broken' => 'chain broken',
			'check' => 'check',
			'check-circle' => 'check circle',
			'check-circle-o' => 'check circle o',
			'check-square' => 'check square',
			'check-square-o' => 'check square o',
			'chevron-circle-down' => 'chevron circle down',
			'chevron-circle-left' => 'chevron circle left',
			'chevron-circle-right' => 'chevron circle right',
			'chevron-circle-up' => 'chevron circle up',
			'chevron-down' => 'chevron down',
			'chevron-left' => 'chevron left',
			'chevron-right' => 'chevron right',
			'chevron-up' => 'chevron up',
			'child' => 'child',
			'circle' => 'circle',
			'circle-o' => 'circle o',
			'circle-o-notch' => 'circle o notch',
			'circle-thin' => 'circle thin',
			'clipboard' => 'clipboard',
			'clock-o' => 'clock o',
			'cloud' => 'cloud',
			'cloud-download' => 'cloud download',
			'cloud-upload' => 'cloud upload',
			'code' => 'code',
			'code-fork' => 'code fork',
			'codepen' => 'codepen',
			'coffee' => 'coffee',
			'cog' => 'cog',
			'cogs' => 'cogs',
			'columns' => 'columns',
			'comment' => 'comment',
			'comment-o' => 'comment o',
			'comments' => 'comments',
			'comments-o' => 'comments o',
			'compass' => 'compass',
			'compress' => 'compress',
			'connectdevelop' => 'connectdevelop',
			'copyright' => 'copyright',
			'credit-card' => 'credit card',
			'crop' => 'crop',
			'crosshairs' => 'crosshairs',
			'css3' => 'css3',
			'cube' => 'cube',
			'cubes' => 'cubes',
			'cutlery' => 'cutlery',
			'dashcube' => 'dashcube',
			'database' => 'database',
			'delicious' => 'delicious',
			'desktop' => 'desktop',
			'deviantart' => 'deviantart',
			'diamond' => 'diamond',
			'digg' => 'digg',
			'dot-circle-o' => 'dot circle o',
			'download' => 'download',
			'dribbble' => 'dribbble',
			'dropbox' => 'dropbox',
			'drupal' => 'drupal',
			'eject' => 'eject',
			'ellipsis-h' => 'ellipsis h',
			'ellipsis-v' => 'ellipsis v',
			'empire' => 'empire',
			'envelope' => 'envelope',
			'envelope-o' => 'envelope o',
			'envelope-square' => 'envelope square',
			'eraser' => 'eraser',
			'eur' => 'eur',
			'exchange' => 'exchange',
			'exclamation' => 'exclamation',
			'exclamation-circle' => 'exclamation circle',
			'exclamation-triangle' => 'exclamation triangle',
			'expand' => 'expand',
			'external-link' => 'external link',
			'external-link-square' => 'external link square',
			'eye' => 'eye',
			'eye-slash' => 'eye slash',
			'eyedropper' => 'eyedropper',
			'facebook' => 'facebook',
			'facebook-official' => 'facebook official',
			'facebook-square' => 'facebook square',
			'fast-backward' => 'fast backward',
			'fast-forward' => 'fast forward',
			'fax' => 'fax',
			'female' => 'female',
			'fighter-jet' => 'fighter jet',
			'file' => 'file',
			'file-archive-o' => 'file archive o',
			'file-audio-o' => 'file audio o',
			'file-code-o' => 'file code o',
			'file-excel-o' => 'file excel o',
			'file-image-o' => 'file image o',
			'file-o' => 'file o',
			'file-pdf-o' => 'file pdf o',
			'file-powerpoint-o' => 'file powerpoint o',
			'file-text' => 'file text',
			'file-text-o' => 'file text o',
			'file-video-o' => 'file video o',
			'file-word-o' => 'file word o',
			'files-o' => 'files o',
			'film' => 'film',
			'filter' => 'filter',
			'fire' => 'fire',
			'fire-extinguisher' => 'fire extinguisher',
			'flag' => 'flag',
			'flag-checkered' => 'flag checkered',
			'flag-o' => 'flag o',
			'flask' => 'flask',
			'flickr' => 'flickr',
			'floppy-o' => 'floppy o',
			'folder' => 'folder',
			'folder-o' => 'folder o',
			'folder-open' => 'folder open',
			'folder-open-o' => 'folder open o',
			'font' => 'font',
			'forumbee' => 'forumbee',
			'forward' => 'forward',
			'foursquare' => 'foursquare',
			'frown-o' => 'frown o',
			'futbol-o' => 'futbol o',
			'gamepad' => 'gamepad',
			'gavel' => 'gavel',
			'gbp' => 'gbp',
			'gift' => 'gift',
			'git' => 'git',
			'git-square' => 'git square',
			'github' => 'github',
			'github-alt' => 'github alt',
			'github-square' => 'github square',
			'glass' => 'glass',
			'globe' => 'globe',
			'google' => 'google',
			'google-plus' => 'google plus',
			'google-plus-square' => 'google plus square',
			'google-wallet' => 'google wallet',
			'graduation-cap' => 'graduation cap',
			'gratipay' => 'gratipay',
			'h-square' => 'h square',
			'hacker-news' => 'hacker news',
			'hand-o-down' => 'hand o down',
			'hand-o-left' => 'hand o left',
			'hand-o-right' => 'hand o right',
			'hand-o-up' => 'hand o up',
			'hdd-o' => 'hdd o',
			'header' => 'header',
			'headphones' => 'headphones',
			'heart' => 'heart',
			'heart-o' => 'heart o',
			'heartbeat' => 'heartbeat',
			'history' => 'history',
			'home' => 'home',
			'hospital-o' => 'hospital o',
			'html5' => 'html5',
			'ils' => 'ils',
			'inbox' => 'inbox',
			'indent' => 'indent',
			'info' => 'info',
			'info-circle' => 'info circle',
			'inr' => 'inr',
			'instagram' => 'instagram',
			'ioxhost' => 'ioxhost',
			'italic' => 'italic',
			'joomla' => 'joomla',
			'jpy' => 'jpy',
			'jsfiddle' => 'jsfiddle',
			'key' => 'key',
			'keyboard-o' => 'keyboard o',
			'krw' => 'krw',
			'language' => 'language',
			'laptop' => 'laptop',
			'lastfm' => 'lastfm',
			'lastfm-square' => 'lastfm square',
			'leaf' => 'leaf',
			'leanpub' => 'leanpub',
			'lemon-o' => 'lemon o',
			'level-down' => 'level down',
			'level-up' => 'level up',
			'life-ring' => 'life ring',
			'lightbulb-o' => 'lightbulb o',
			'line-chart' => 'line chart',
			'link' => 'link',
			'linkedin' => 'linkedin',
			'linkedin-square' => 'linkedin square',
			'linux' => 'linux',
			'list' => 'list',
			'list-alt' => 'list alt',
			'list-ol' => 'list ol',
			'list-ul' => 'list ul',
			'location-arrow' => 'location arrow',
			'lock' => 'lock',
			'long-arrow-down' => 'long arrow down',
			'long-arrow-left' => 'long arrow left',
			'long-arrow-right' => 'long arrow right',
			'long-arrow-up' => 'long arrow up',
			'magic' => 'magic',
			'magnet' => 'magnet',
			'male' => 'male',
			'map-marker' => 'map marker',
			'mars' => 'mars',
			'mars-double' => 'mars double',
			'mars-stroke' => 'mars stroke',
			'mars-stroke-h' => 'mars stroke h',
			'mars-stroke-v' => 'mars stroke v',
			'maxcdn' => 'maxcdn',
			'meanpath' => 'meanpath',
			'medium' => 'medium',
			'medkit' => 'medkit',
			'meh-o' => 'meh o',
			'mercury' => 'mercury',
			'microphone' => 'microphone',
			'microphone-slash' => 'microphone slash',
			'minus' => 'minus',
			'minus-circle' => 'minus circle',
			'minus-square' => 'minus square',
			'minus-square-o' => 'minus square o',
			'mobile' => 'mobile',
			'money' => 'money',
			'moon-o' => 'moon o',
			'motorcycle' => 'motorcycle',
			'music' => 'music',
			'neuter' => 'neuter',
			'newspaper-o' => 'newspaper o',
			'openid' => 'openid',
			'outdent' => 'outdent',
			'pagelines' => 'pagelines',
			'paint-brush' => 'paint brush',
			'paper-plane' => 'paper plane',
			'paper-plane-o' => 'paper plane o',
			'paperclip' => 'paperclip',
			'paragraph' => 'paragraph',
			'pause' => 'pause',
			'paw' => 'paw',
			'paypal' => 'paypal',
			'pencil' => 'pencil',
			'pencil-square' => 'pencil square',
			'pencil-square-o' => 'pencil square o',
			'phone' => 'phone',
			'phone-square' => 'phone square',
			'picture-o' => 'picture o',
			'pie-chart' => 'pie chart',
			'pied-piper' => 'pied piper',
			'pied-piper-alt' => 'pied piper alt',
			'pinterest' => 'pinterest',
			'pinterest-p' => 'pinterest p',
			'pinterest-square' => 'pinterest square',
			'plane' => 'plane',
			'play' => 'play',
			'play-circle' => 'play circle',
			'play-circle-o' => 'play circle o',
			'plug' => 'plug',
			'plus' => 'plus',
			'plus-circle' => 'plus circle',
			'plus-square' => 'plus square',
			'plus-square-o' => 'plus square o',
			'power-off' => 'power off',
			'print' => 'print',
			'puzzle-piece' => 'puzzle piece',
			'qq' => 'qq',
			'qrcode' => 'qrcode',
			'question' => 'question',
			'question-circle' => 'question circle',
			'quote-left' => 'quote left',
			'quote-right' => 'quote right',
			'random' => 'random',
			'rebel' => 'rebel',
			'recycle' => 'recycle',
			'reddit' => 'reddit',
			'reddit-square' => 'reddit square',
			'refresh' => 'refresh',
			'renren' => 'renren',
			'repeat' => 'repeat',
			'reply' => 'reply',
			'reply-all' => 'reply all',
			'retweet' => 'retweet',
			'road' => 'road',
			'rocket' => 'rocket',
			'rss' => 'rss',
			'rss-square' => 'rss square',
			'rub' => 'rub',
			'scissors' => 'scissors',
			'search' => 'search',
			'search-minus' => 'search minus',
			'search-plus' => 'search plus',
			'sellsy' => 'sellsy',
			'server' => 'server',
			'share' => 'share',
			'share-alt' => 'share alt',
			'share-alt-square' => 'share alt square',
			'share-square' => 'share square',
			'share-square-o' => 'share square o',
			'shield' => 'shield',
			'ship' => 'ship',
			'shirtsinbulk' => 'shirtsinbulk',
			'shopping-cart' => 'shopping cart',
			'sign-in' => 'sign in',
			'sign-out' => 'sign out',
			'signal' => 'signal',
			'simplybuilt' => 'simplybuilt',
			'sitemap' => 'sitemap',
			'skyatlas' => 'skyatlas',
			'skype' => 'skype',
			'slack' => 'slack',
			'sliders' => 'sliders',
			'slideshare' => 'slideshare',
			'smile-o' => 'smile o',
			'sort' => 'sort',
			'sort-alpha-asc' => 'sort alpha asc',
			'sort-alpha-desc' => 'sort alpha desc',
			'sort-amount-asc' => 'sort amount asc',
			'sort-amount-desc' => 'sort amount desc',
			'sort-asc' => 'sort asc',
			'sort-desc' => 'sort desc',
			'sort-numeric-asc' => 'sort numeric asc',
			'sort-numeric-desc' => 'sort numeric desc',
			'soundcloud' => 'soundcloud',
			'space-shuttle' => 'space shuttle',
			'spinner' => 'spinner',
			'spoon' => 'spoon',
			'spotify' => 'spotify',
			'square' => 'square',
			'square-o' => 'square o',
			'stack-exchange' => 'stack exchange',
			'stack-overflow' => 'stack overflow',
			'star' => 'star',
			'star-half' => 'star half',
			'star-half-o' => 'star half o',
			'star-o' => 'star o',
			'steam' => 'steam',
			'steam-square' => 'steam square',
			'step-backward' => 'step backward',
			'step-forward' => 'step forward',
			'stethoscope' => 'stethoscope',
			'stop' => 'stop',
			'street-view' => 'street view',
			'strikethrough' => 'strikethrough',
			'stumbleupon' => 'stumbleupon',
			'stumbleupon-circle' => 'stumbleupon circle',
			'subscript' => 'subscript',
			'subway' => 'subway',
			'suitcase' => 'suitcase',
			'sun-o' => 'sun o',
			'superscript' => 'superscript',
			'table' => 'table',
			'tablet' => 'tablet',
			'tachometer' => 'tachometer',
			'tag' => 'tag',
			'tags' => 'tags',
			'tasks' => 'tasks',
			'taxi' => 'taxi',
			'tencent-weibo' => 'tencent weibo',
			'terminal' => 'terminal',
			'text-height' => 'text height',
			'text-width' => 'text width',
			'th' => 'th',
			'th-large' => 'th large',
			'th-list' => 'th list',
			'thumb-tack' => 'thumb tack',
			'thumbs-down' => 'thumbs down',
			'thumbs-o-down' => 'thumbs o down',
			'thumbs-o-up' => 'thumbs o up',
			'thumbs-up' => 'thumbs up',
			'ticket' => 'ticket',
			'times' => 'times',
			'times-circle' => 'times circle',
			'times-circle-o' => 'times circle o',
			'tint' => 'tint',
			'toggle-off' => 'toggle off',
			'toggle-on' => 'toggle on',
			'train' => 'train',
			'transgender' => 'transgender',
			'transgender-alt' => 'transgender alt',
			'trash' => 'trash',
			'trash-o' => 'trash o',
			'tree' => 'tree',
			'trello' => 'trello',
			'trophy' => 'trophy',
			'truck' => 'truck',
			'try' => 'try',
			'tty' => 'tty',
			'tumblr' => 'tumblr',
			'tumblr-square' => 'tumblr square',
			'twitch' => 'twitch',
			'twitter' => 'twitter',
			'twitter-square' => 'twitter square',
			'umbrella' => 'umbrella',
			'underline' => 'underline',
			'undo' => 'undo',
			'university' => 'university',
			'unlock' => 'unlock',
			'unlock-alt' => 'unlock alt',
			'upload' => 'upload',
			'usd' => 'usd',
			'user' => 'user',
			'user-md' => 'user md',
			'user-plus' => 'user plus',
			'user-secret' => 'user secret',
			'user-times' => 'user times',
			'users' => 'users',
			'venus' => 'venus',
			'venus-double' => 'venus double',
			'venus-mars' => 'venus mars',
			'viacoin' => 'viacoin',
			'video-camera' => 'video camera',
			'vimeo-square' => 'vimeo square',
			'vine' => 'vine',
			'vk' => 'vk',
			'volume-down' => 'volume down',
			'volume-off' => 'volume off',
			'volume-up' => 'volume up',
			'weibo' => 'weibo',
			'weixin' => 'weixin',
			'whatsapp' => 'whatsapp',
			'wheelchair' => 'wheelchair',
			'wifi' => 'wifi',
			'windows' => 'windows',
			'wordpress' => 'wordpress',
			'wrench' => 'wrench',
			'xing' => 'xing',
			'xing-square' => 'xing square',
			'yahoo' => 'yahoo',
			'yelp' => 'yelp',
			'youtube' => 'youtube',
			'youtube-play' => 'youtube play',
			'youtube-square' => 'youtube square',

             );
        $instance = wp_parse_args($instance, $defaults);
        extract($instance);
        ?>
        <p class="description">
            <label for="<?php echo $this->get_field_id('title') ?>">
                <?php _e("Title", 'oblivion') ?>
                <?php echo field_input('title', $block_id, $title, $size = 'full') ?>
            </label>
        </p>
            <p class="description fourth">
            <label for="<?php echo $this->get_field_id('icon') ?>">
                <?php _e("Icon", 'oblivion') ?><br/>
                <?php echo field_select('icon', $block_id, $icon_options, $icon, $block_id); ?>
            </label>
        </p>
        <p class="description">
            <label for="<?php echo $this->get_field_id('text') ?>">
                <?php _e("Content", 'oblivion') ?>
                <?php echo field_textarea('text', $block_id, $text, $size = 'full',  $number == '__i__' ? false : true) ?>
            </label>
        </p>
        <?php
    }
    function pbblock($instance) {
        extract($instance);
            echo '<div class="text-container centered bgpattern charblock">
                <span class="icon i-with-animation " data-animation="grow-in" data-delay="">';
                  switch($icon) {
                        case 'none': break;
                        case 'adjust'  :  echo  '<span class=" fa fa-adjust"></span>'; break;
						case 'adn'  :  echo  '<span class=" fa fa-adn"></span>'; break;
						case 'align-center'  :  echo  '<span class=" fa fa-align-center"></span>'; break;
						case 'align-justify'  :  echo  '<span class=" fa fa-align-justify"></span>'; break;
						case 'align-left'  :  echo  '<span class=" fa fa-align-left"></span>'; break;
						case 'align-right'  :  echo  '<span class=" fa fa-align-right"></span>'; break;
						case 'ambulance'  :  echo  '<span class=" fa fa-ambulance"></span>'; break;
						case 'anchor'  :  echo  '<span class=" fa fa-anchor"></span>'; break;
						case 'android'  :  echo  '<span class=" fa fa-android"></span>'; break;
						case 'angellist'  :  echo  '<span class=" fa fa-angellist"></span>'; break;
						case 'angle-double-down'  :  echo  '<span class=" fa fa-angle-double-down"></span>'; break;
						case 'angle-double-left'  :  echo  '<span class=" fa fa-angle-double-left"></span>'; break;
						case 'angle-double-right'  :  echo  '<span class=" fa fa-angle-double-right"></span>'; break;
						case 'angle-double-up'  :  echo  '<span class=" fa fa-angle-double-up"></span>'; break;
						case 'angle-down'  :  echo  '<span class=" fa fa-angle-down"></span>'; break;
						case 'angle-left'  :  echo  '<span class=" fa fa-angle-left"></span>'; break;
						case 'angle-right'  :  echo  '<span class=" fa fa-angle-right"></span>'; break;
						case 'angle-up'  :  echo  '<span class=" fa fa-angle-up"></span>'; break;
						case 'apple'  :  echo  '<span class=" fa fa-apple"></span>'; break;
						case 'archive'  :  echo  '<span class=" fa fa-archive"></span>'; break;
						case 'area-chart'  :  echo  '<span class=" fa fa-area-chart"></span>'; break;
						case 'arrow-circle-down'  :  echo  '<span class=" fa fa-arrow-circle-down"></span>'; break;
						case 'arrow-circle-left'  :  echo  '<span class=" fa fa-arrow-circle-left"></span>'; break;
						case 'arrow-circle-o-down'  :  echo  '<span class=" fa fa-arrow-circle-o-down"></span>'; break;
						case 'arrow-circle-o-left'  :  echo  '<span class=" fa fa-arrow-circle-o-left"></span>'; break;
						case 'arrow-circle-o-right'  :  echo  '<span class=" fa fa-arrow-circle-o-right"></span>'; break;
						case 'arrow-circle-o-up'  :  echo  '<span class=" fa fa-arrow-circle-o-up"></span>'; break;
						case 'arrow-circle-right'  :  echo  '<span class=" fa fa-arrow-circle-right"></span>'; break;
						case 'arrow-circle-up'  :  echo  '<span class=" fa fa-arrow-circle-up"></span>'; break;
						case 'arrow-down'  :  echo  '<span class=" fa fa-arrow-down"></span>'; break;
						case 'arrow-left'  :  echo  '<span class=" fa fa-arrow-left"></span>'; break;
						case 'arrow-right'  :  echo  '<span class=" fa fa-arrow-right"></span>'; break;
						case 'arrow-up'  :  echo  '<span class=" fa fa-arrow-up"></span>'; break;
						case 'arrows'  :  echo  '<span class=" fa fa-arrows"></span>'; break;
						case 'arrows-alt'  :  echo  '<span class=" fa fa-arrows-alt"></span>'; break;
						case 'arrows-h'  :  echo  '<span class=" fa fa-arrows-h"></span>'; break;
						case 'arrows-v'  :  echo  '<span class=" fa fa-arrows-v"></span>'; break;
						case 'asterisk'  :  echo  '<span class=" fa fa-asterisk"></span>'; break;
						case 'at'  :  echo  '<span class=" fa fa-at"></span>'; break;
						case 'backward'  :  echo  '<span class=" fa fa-backward"></span>'; break;
						case 'ban'  :  echo  '<span class=" fa fa-ban"></span>'; break;
						case 'bar-chart'  :  echo  '<span class=" fa fa-bar-chart"></span>'; break;
						case 'barcode'  :  echo  '<span class=" fa fa-barcode"></span>'; break;
						case 'bars'  :  echo  '<span class=" fa fa-bars"></span>'; break;
						case 'bed'  :  echo  '<span class=" fa fa-bed"></span>'; break;
						case 'beer'  :  echo  '<span class=" fa fa-beer"></span>'; break;
						case 'behance'  :  echo  '<span class=" fa fa-behance"></span>'; break;
						case 'behance-square'  :  echo  '<span class=" fa fa-behance-square"></span>'; break;
						case 'bell'  :  echo  '<span class=" fa fa-bell"></span>'; break;
						case 'bell-o'  :  echo  '<span class=" fa fa-bell-o"></span>'; break;
						case 'bell-slash'  :  echo  '<span class=" fa fa-bell-slash"></span>'; break;
						case 'bell-slash-o'  :  echo  '<span class=" fa fa-bell-slash-o"></span>'; break;
						case 'bicycle'  :  echo  '<span class=" fa fa-bicycle"></span>'; break;
						case 'binoculars'  :  echo  '<span class=" fa fa-binoculars"></span>'; break;
						case 'birthday-cake'  :  echo  '<span class=" fa fa-birthday-cake"></span>'; break;
						case 'bitbucket'  :  echo  '<span class=" fa fa-bitbucket"></span>'; break;
						case 'bitbucket-square'  :  echo  '<span class=" fa fa-bitbucket-square"></span>'; break;
						case 'bold'  :  echo  '<span class=" fa fa-bold"></span>'; break;
						case 'bolt'  :  echo  '<span class=" fa fa-bolt"></span>'; break;
						case 'bomb'  :  echo  '<span class=" fa fa-bomb"></span>'; break;
						case 'book'  :  echo  '<span class=" fa fa-book"></span>'; break;
						case 'bookmark'  :  echo  '<span class=" fa fa-bookmark"></span>'; break;
						case 'bookmark-o'  :  echo  '<span class=" fa fa-bookmark-o"></span>'; break;
						case 'briefcase'  :  echo  '<span class=" fa fa-briefcase"></span>'; break;
						case 'btc'  :  echo  '<span class=" fa fa-btc"></span>'; break;
						case 'bug'  :  echo  '<span class=" fa fa-bug"></span>'; break;
						case 'building'  :  echo  '<span class=" fa fa-building"></span>'; break;
						case 'building-o'  :  echo  '<span class=" fa fa-building-o"></span>'; break;
						case 'bullhorn'  :  echo  '<span class=" fa fa-bullhorn"></span>'; break;
						case 'bullseye'  :  echo  '<span class=" fa fa-bullseye"></span>'; break;
						case 'bus'  :  echo  '<span class=" fa fa-bus"></span>'; break;
						case 'buysellads'  :  echo  '<span class=" fa fa-buysellads"></span>'; break;
						case 'calculator'  :  echo  '<span class=" fa fa-calculator"></span>'; break;
						case 'calendar'  :  echo  '<span class=" fa fa-calendar"></span>'; break;
						case 'calendar-o'  :  echo  '<span class=" fa fa-calendar-o"></span>'; break;
						case 'camera'  :  echo  '<span class=" fa fa-camera"></span>'; break;
						case 'camera-retro'  :  echo  '<span class=" fa fa-camera-retro"></span>'; break;
						case 'car'  :  echo  '<span class=" fa fa-car"></span>'; break;
						case 'caret-down'  :  echo  '<span class=" fa fa-caret-down"></span>'; break;
						case 'caret-left'  :  echo  '<span class=" fa fa-caret-left"></span>'; break;
						case 'caret-right'  :  echo  '<span class=" fa fa-caret-right"></span>'; break;
						case 'caret-square-o-down'  :  echo  '<span class=" fa fa-caret-square-o-down"></span>'; break;
						case 'caret-square-o-left'  :  echo  '<span class=" fa fa-caret-square-o-left"></span>'; break;
						case 'caret-square-o-right'  :  echo  '<span class=" fa fa-caret-square-o-right"></span>'; break;
						case 'caret-square-o-up'  :  echo  '<span class=" fa fa-caret-square-o-up"></span>'; break;
						case 'caret-up'  :  echo  '<span class=" fa fa-caret-up"></span>'; break;
						case 'cart-arrow-down'  :  echo  '<span class=" fa fa-cart-arrow-down"></span>'; break;
						case 'cart-plus'  :  echo  '<span class=" fa fa-cart-plus"></span>'; break;
						case 'cc'  :  echo  '<span class=" fa fa-cc"></span>'; break;
						case 'cc-amex'  :  echo  '<span class=" fa fa-cc-amex"></span>'; break;
						case 'cc-discover'  :  echo  '<span class=" fa fa-cc-discover"></span>'; break;
						case 'cc-mastercard'  :  echo  '<span class=" fa fa-cc-mastercard"></span>'; break;
						case 'cc-paypal'  :  echo  '<span class=" fa fa-cc-paypal"></span>'; break;
						case 'cc-stripe'  :  echo  '<span class=" fa fa-cc-stripe"></span>'; break;
						case 'cc-visa'  :  echo  '<span class=" fa fa-cc-visa"></span>'; break;
						case 'certificate'  :  echo  '<span class=" fa fa-certificate"></span>'; break;
						case 'chain-broken'  :  echo  '<span class=" fa fa-chain-broken"></span>'; break;
						case 'check'  :  echo  '<span class=" fa fa-check"></span>'; break;
						case 'check-circle'  :  echo  '<span class=" fa fa-check-circle"></span>'; break;
						case 'check-circle-o'  :  echo  '<span class=" fa fa-check-circle-o"></span>'; break;
						case 'check-square'  :  echo  '<span class=" fa fa-check-square"></span>'; break;
						case 'check-square-o'  :  echo  '<span class=" fa fa-check-square-o"></span>'; break;
						case 'chevron-circle-down'  :  echo  '<span class=" fa fa-chevron-circle-down"></span>'; break;
						case 'chevron-circle-left'  :  echo  '<span class=" fa fa-chevron-circle-left"></span>'; break;
						case 'chevron-circle-right'  :  echo  '<span class=" fa fa-chevron-circle-right"></span>'; break;
						case 'chevron-circle-up'  :  echo  '<span class=" fa fa-chevron-circle-up"></span>'; break;
						case 'chevron-down'  :  echo  '<span class=" fa fa-chevron-down"></span>'; break;
						case 'chevron-left'  :  echo  '<span class=" fa fa-chevron-left"></span>'; break;
						case 'chevron-right'  :  echo  '<span class=" fa fa-chevron-right"></span>'; break;
						case 'chevron-up'  :  echo  '<span class=" fa fa-chevron-up"></span>'; break;
						case 'child'  :  echo  '<span class=" fa fa-child"></span>'; break;
						case 'circle'  :  echo  '<span class=" fa fa-circle"></span>'; break;
						case 'circle-o'  :  echo  '<span class=" fa fa-circle-o"></span>'; break;
						case 'circle-o-notch'  :  echo  '<span class=" fa fa-circle-o-notch"></span>'; break;
						case 'circle-thin'  :  echo  '<span class=" fa fa-circle-thin"></span>'; break;
						case 'clipboard'  :  echo  '<span class=" fa fa-clipboard"></span>'; break;
						case 'clock-o'  :  echo  '<span class=" fa fa-clock-o"></span>'; break;
						case 'cloud'  :  echo  '<span class=" fa fa-cloud"></span>'; break;
						case 'cloud-download'  :  echo  '<span class=" fa fa-cloud-download"></span>'; break;
						case 'cloud-upload'  :  echo  '<span class=" fa fa-cloud-upload"></span>'; break;
						case 'code'  :  echo  '<span class=" fa fa-code"></span>'; break;
						case 'code-fork'  :  echo  '<span class=" fa fa-code-fork"></span>'; break;
						case 'codepen'  :  echo  '<span class=" fa fa-codepen"></span>'; break;
						case 'coffee'  :  echo  '<span class=" fa fa-coffee"></span>'; break;
						case 'cog'  :  echo  '<span class=" fa fa-cog"></span>'; break;
						case 'cogs'  :  echo  '<span class=" fa fa-cogs"></span>'; break;
						case 'columns'  :  echo  '<span class=" fa fa-columns"></span>'; break;
						case 'comment'  :  echo  '<span class=" fa fa-comment"></span>'; break;
						case 'comment-o'  :  echo  '<span class=" fa fa-comment-o"></span>'; break;
						case 'comments'  :  echo  '<span class=" fa fa-comments"></span>'; break;
						case 'comments-o'  :  echo  '<span class=" fa fa-comments-o"></span>'; break;
						case 'compass'  :  echo  '<span class=" fa fa-compass"></span>'; break;
						case 'compress'  :  echo  '<span class=" fa fa-compress"></span>'; break;
						case 'connectdevelop'  :  echo  '<span class=" fa fa-connectdevelop"></span>'; break;
						case 'copyright'  :  echo  '<span class=" fa fa-copyright"></span>'; break;
						case 'credit-card'  :  echo  '<span class=" fa fa-credit-card"></span>'; break;
						case 'crop'  :  echo  '<span class=" fa fa-crop"></span>'; break;
						case 'crosshairs'  :  echo  '<span class=" fa fa-crosshairs"></span>'; break;
						case 'css3'  :  echo  '<span class=" fa fa-css3"></span>'; break;
						case 'cube'  :  echo  '<span class=" fa fa-cube"></span>'; break;
						case 'cubes'  :  echo  '<span class=" fa fa-cubes"></span>'; break;
						case 'cutlery'  :  echo  '<span class=" fa fa-cutlery"></span>'; break;
						case 'dashcube'  :  echo  '<span class=" fa fa-dashcube"></span>'; break;
						case 'database'  :  echo  '<span class=" fa fa-database"></span>'; break;
						case 'delicious'  :  echo  '<span class=" fa fa-delicious"></span>'; break;
						case 'desktop'  :  echo  '<span class=" fa fa-desktop"></span>'; break;
						case 'deviantart'  :  echo  '<span class=" fa fa-deviantart"></span>'; break;
						case 'diamond'  :  echo  '<span class=" fa fa-diamond"></span>'; break;
						case 'digg'  :  echo  '<span class=" fa fa-digg"></span>'; break;
						case 'dot-circle-o'  :  echo  '<span class=" fa fa-dot-circle-o"></span>'; break;
						case 'download'  :  echo  '<span class=" fa fa-download"></span>'; break;
						case 'dribbble'  :  echo  '<span class=" fa fa-dribbble"></span>'; break;
						case 'dropbox'  :  echo  '<span class=" fa fa-dropbox"></span>'; break;
						case 'drupal'  :  echo  '<span class=" fa fa-drupal"></span>'; break;
						case 'eject'  :  echo  '<span class=" fa fa-eject"></span>'; break;
						case 'ellipsis-h'  :  echo  '<span class=" fa fa-ellipsis-h"></span>'; break;
						case 'ellipsis-v'  :  echo  '<span class=" fa fa-ellipsis-v"></span>'; break;
						case 'empire'  :  echo  '<span class=" fa fa-empire"></span>'; break;
						case 'envelope'  :  echo  '<span class=" fa fa-envelope"></span>'; break;
						case 'envelope-o'  :  echo  '<span class=" fa fa-envelope-o"></span>'; break;
						case 'envelope-square'  :  echo  '<span class=" fa fa-envelope-square"></span>'; break;
						case 'eraser'  :  echo  '<span class=" fa fa-eraser"></span>'; break;
						case 'eur'  :  echo  '<span class=" fa fa-eur"></span>'; break;
						case 'exchange'  :  echo  '<span class=" fa fa-exchange"></span>'; break;
						case 'exclamation'  :  echo  '<span class=" fa fa-exclamation"></span>'; break;
						case 'exclamation-circle'  :  echo  '<span class=" fa fa-exclamation-circle"></span>'; break;
						case 'exclamation-triangle'  :  echo  '<span class=" fa fa-exclamation-triangle"></span>'; break;
						case 'expand'  :  echo  '<span class=" fa fa-expand"></span>'; break;
						case 'external-link'  :  echo  '<span class=" fa fa-external-link"></span>'; break;
						case 'external-link-square'  :  echo  '<span class=" fa fa-external-link-square"></span>'; break;
						case 'eye'  :  echo  '<span class=" fa fa-eye"></span>'; break;
						case 'eye-slash'  :  echo  '<span class=" fa fa-eye-slash"></span>'; break;
						case 'eyedropper'  :  echo  '<span class=" fa fa-eyedropper"></span>'; break;
						case 'facebook'  :  echo  '<span class=" fa fa-facebook"></span>'; break;
						case 'facebook-official'  :  echo  '<span class=" fa fa-facebook-official"></span>'; break;
						case 'facebook-square'  :  echo  '<span class=" fa fa-facebook-square"></span>'; break;
						case 'fast-backward'  :  echo  '<span class=" fa fa-fast-backward"></span>'; break;
						case 'fast-forward'  :  echo  '<span class=" fa fa-fast-forward"></span>'; break;
						case 'fax'  :  echo  '<span class=" fa fa-fax"></span>'; break;
						case 'female'  :  echo  '<span class=" fa fa-female"></span>'; break;
						case 'fighter-jet'  :  echo  '<span class=" fa fa-fighter-jet"></span>'; break;
						case 'file'  :  echo  '<span class=" fa fa-file"></span>'; break;
						case 'file-archive-o'  :  echo  '<span class=" fa fa-file-archive-o"></span>'; break;
						case 'file-audio-o'  :  echo  '<span class=" fa fa-file-audio-o"></span>'; break;
						case 'file-code-o'  :  echo  '<span class=" fa fa-file-code-o"></span>'; break;
						case 'file-excel-o'  :  echo  '<span class=" fa fa-file-excel-o"></span>'; break;
						case 'file-image-o'  :  echo  '<span class=" fa fa-file-image-o"></span>'; break;
						case 'file-o'  :  echo  '<span class=" fa fa-file-o"></span>'; break;
						case 'file-pdf-o'  :  echo  '<span class=" fa fa-file-pdf-o"></span>'; break;
						case 'file-powerpoint-o'  :  echo  '<span class=" fa fa-file-powerpoint-o"></span>'; break;
						case 'file-text'  :  echo  '<span class=" fa fa-file-text"></span>'; break;
						case 'file-text-o'  :  echo  '<span class=" fa fa-file-text-o"></span>'; break;
						case 'file-video-o'  :  echo  '<span class=" fa fa-file-video-o"></span>'; break;
						case 'file-word-o'  :  echo  '<span class=" fa fa-file-word-o"></span>'; break;
						case 'files-o'  :  echo  '<span class=" fa fa-files-o"></span>'; break;
						case 'film'  :  echo  '<span class=" fa fa-film"></span>'; break;
						case 'filter'  :  echo  '<span class=" fa fa-filter"></span>'; break;
						case 'fire'  :  echo  '<span class=" fa fa-fire"></span>'; break;
						case 'fire-extinguisher'  :  echo  '<span class=" fa fa-fire-extinguisher"></span>'; break;
						case 'flag'  :  echo  '<span class=" fa fa-flag"></span>'; break;
						case 'flag-checkered'  :  echo  '<span class=" fa fa-flag-checkered"></span>'; break;
						case 'flag-o'  :  echo  '<span class=" fa fa-flag-o"></span>'; break;
						case 'flask'  :  echo  '<span class=" fa fa-flask"></span>'; break;
						case 'flickr'  :  echo  '<span class=" fa fa-flickr"></span>'; break;
						case 'floppy-o'  :  echo  '<span class=" fa fa-floppy-o"></span>'; break;
						case 'folder'  :  echo  '<span class=" fa fa-folder"></span>'; break;
						case 'folder-o'  :  echo  '<span class=" fa fa-folder-o"></span>'; break;
						case 'folder-open'  :  echo  '<span class=" fa fa-folder-open"></span>'; break;
						case 'folder-open-o'  :  echo  '<span class=" fa fa-folder-open-o"></span>'; break;
						case 'font'  :  echo  '<span class=" fa fa-font"></span>'; break;
						case 'forumbee'  :  echo  '<span class=" fa fa-forumbee"></span>'; break;
						case 'forward'  :  echo  '<span class=" fa fa-forward"></span>'; break;
						case 'foursquare'  :  echo  '<span class=" fa fa-foursquare"></span>'; break;
						case 'frown-o'  :  echo  '<span class=" fa fa-frown-o"></span>'; break;
						case 'futbol-o'  :  echo  '<span class=" fa fa-futbol-o"></span>'; break;
						case 'gamepad'  :  echo  '<span class=" fa fa-gamepad"></span>'; break;
						case 'gavel'  :  echo  '<span class=" fa fa-gavel"></span>'; break;
						case 'gbp'  :  echo  '<span class=" fa fa-gbp"></span>'; break;
						case 'gift'  :  echo  '<span class=" fa fa-gift"></span>'; break;
						case 'git'  :  echo  '<span class=" fa fa-git"></span>'; break;
						case 'git-square'  :  echo  '<span class=" fa fa-git-square"></span>'; break;
						case 'github'  :  echo  '<span class=" fa fa-github"></span>'; break;
						case 'github-alt'  :  echo  '<span class=" fa fa-github-alt"></span>'; break;
						case 'github-square'  :  echo  '<span class=" fa fa-github-square"></span>'; break;
						case 'glass'  :  echo  '<span class=" fa fa-glass"></span>'; break;
						case 'globe'  :  echo  '<span class=" fa fa-globe"></span>'; break;
						case 'google'  :  echo  '<span class=" fa fa-google"></span>'; break;
						case 'google-plus'  :  echo  '<span class=" fa fa-google-plus"></span>'; break;
						case 'google-plus-square'  :  echo  '<span class=" fa fa-google-plus-square"></span>'; break;
						case 'google-wallet'  :  echo  '<span class=" fa fa-google-wallet"></span>'; break;
						case 'graduation-cap'  :  echo  '<span class=" fa fa-graduation-cap"></span>'; break;
						case 'gratipay'  :  echo  '<span class=" fa fa-gratipay"></span>'; break;
						case 'h-square'  :  echo  '<span class=" fa fa-h-square"></span>'; break;
						case 'hacker-news'  :  echo  '<span class=" fa fa-hacker-news"></span>'; break;
						case 'hand-o-down'  :  echo  '<span class=" fa fa-hand-o-down"></span>'; break;
						case 'hand-o-left'  :  echo  '<span class=" fa fa-hand-o-left"></span>'; break;
						case 'hand-o-right'  :  echo  '<span class=" fa fa-hand-o-right"></span>'; break;
						case 'hand-o-up'  :  echo  '<span class=" fa fa-hand-o-up"></span>'; break;
						case 'hdd-o'  :  echo  '<span class=" fa fa-hdd-o"></span>'; break;
						case 'header'  :  echo  '<span class=" fa fa-header"></span>'; break;
						case 'headphones'  :  echo  '<span class=" fa fa-headphones"></span>'; break;
						case 'heart'  :  echo  '<span class=" fa fa-heart"></span>'; break;
						case 'heart-o'  :  echo  '<span class=" fa fa-heart-o"></span>'; break;
						case 'heartbeat'  :  echo  '<span class=" fa fa-heartbeat"></span>'; break;
						case 'history'  :  echo  '<span class=" fa fa-history"></span>'; break;
						case 'home'  :  echo  '<span class=" fa fa-home"></span>'; break;
						case 'hospital-o'  :  echo  '<span class=" fa fa-hospital-o"></span>'; break;
						case 'html5'  :  echo  '<span class=" fa fa-html5"></span>'; break;
						case 'ils'  :  echo  '<span class=" fa fa-ils"></span>'; break;
						case 'inbox'  :  echo  '<span class=" fa fa-inbox"></span>'; break;
						case 'indent'  :  echo  '<span class=" fa fa-indent"></span>'; break;
						case 'info'  :  echo  '<span class=" fa fa-info"></span>'; break;
						case 'info-circle'  :  echo  '<span class=" fa fa-info-circle"></span>'; break;
						case 'inr'  :  echo  '<span class=" fa fa-inr"></span>'; break;
						case 'instagram'  :  echo  '<span class=" fa fa-instagram"></span>'; break;
						case 'ioxhost'  :  echo  '<span class=" fa fa-ioxhost"></span>'; break;
						case 'italic'  :  echo  '<span class=" fa fa-italic"></span>'; break;
						case 'joomla'  :  echo  '<span class=" fa fa-joomla"></span>'; break;
						case 'jpy'  :  echo  '<span class=" fa fa-jpy"></span>'; break;
						case 'jsfiddle'  :  echo  '<span class=" fa fa-jsfiddle"></span>'; break;
						case 'key'  :  echo  '<span class=" fa fa-key"></span>'; break;
						case 'keyboard-o'  :  echo  '<span class=" fa fa-keyboard-o"></span>'; break;
						case 'krw'  :  echo  '<span class=" fa fa-krw"></span>'; break;
						case 'language'  :  echo  '<span class=" fa fa-language"></span>'; break;
						case 'laptop'  :  echo  '<span class=" fa fa-laptop"></span>'; break;
						case 'lastfm'  :  echo  '<span class=" fa fa-lastfm"></span>'; break;
						case 'lastfm-square'  :  echo  '<span class=" fa fa-lastfm-square"></span>'; break;
						case 'leaf'  :  echo  '<span class=" fa fa-leaf"></span>'; break;
						case 'leanpub'  :  echo  '<span class=" fa fa-leanpub"></span>'; break;
						case 'lemon-o'  :  echo  '<span class=" fa fa-lemon-o"></span>'; break;
						case 'level-down'  :  echo  '<span class=" fa fa-level-down"></span>'; break;
						case 'level-up'  :  echo  '<span class=" fa fa-level-up"></span>'; break;
						case 'life-ring'  :  echo  '<span class=" fa fa-life-ring"></span>'; break;
						case 'lightbulb-o'  :  echo  '<span class=" fa fa-lightbulb-o"></span>'; break;
						case 'line-chart'  :  echo  '<span class=" fa fa-line-chart"></span>'; break;
						case 'link'  :  echo  '<span class=" fa fa-link"></span>'; break;
						case 'linkedin'  :  echo  '<span class=" fa fa-linkedin"></span>'; break;
						case 'linkedin-square'  :  echo  '<span class=" fa fa-linkedin-square"></span>'; break;
						case 'linux'  :  echo  '<span class=" fa fa-linux"></span>'; break;
						case 'list'  :  echo  '<span class=" fa fa-list"></span>'; break;
						case 'list-alt'  :  echo  '<span class=" fa fa-list-alt"></span>'; break;
						case 'list-ol'  :  echo  '<span class=" fa fa-list-ol"></span>'; break;
						case 'list-ul'  :  echo  '<span class=" fa fa-list-ul"></span>'; break;
						case 'location-arrow'  :  echo  '<span class=" fa fa-location-arrow"></span>'; break;
						case 'lock'  :  echo  '<span class=" fa fa-lock"></span>'; break;
						case 'long-arrow-down'  :  echo  '<span class=" fa fa-long-arrow-down"></span>'; break;
						case 'long-arrow-left'  :  echo  '<span class=" fa fa-long-arrow-left"></span>'; break;
						case 'long-arrow-right'  :  echo  '<span class=" fa fa-long-arrow-right"></span>'; break;
						case 'long-arrow-up'  :  echo  '<span class=" fa fa-long-arrow-up"></span>'; break;
						case 'magic'  :  echo  '<span class=" fa fa-magic"></span>'; break;
						case 'magnet'  :  echo  '<span class=" fa fa-magnet"></span>'; break;
						case 'male'  :  echo  '<span class=" fa fa-male"></span>'; break;
						case 'map-marker'  :  echo  '<span class=" fa fa-map-marker"></span>'; break;
						case 'mars'  :  echo  '<span class=" fa fa-mars"></span>'; break;
						case 'mars-double'  :  echo  '<span class=" fa fa-mars-double"></span>'; break;
						case 'mars-stroke'  :  echo  '<span class=" fa fa-mars-stroke"></span>'; break;
						case 'mars-stroke-h'  :  echo  '<span class=" fa fa-mars-stroke-h"></span>'; break;
						case 'mars-stroke-v'  :  echo  '<span class=" fa fa-mars-stroke-v"></span>'; break;
						case 'maxcdn'  :  echo  '<span class=" fa fa-maxcdn"></span>'; break;
						case 'meanpath'  :  echo  '<span class=" fa fa-meanpath"></span>'; break;
						case 'medium'  :  echo  '<span class=" fa fa-medium"></span>'; break;
						case 'medkit'  :  echo  '<span class=" fa fa-medkit"></span>'; break;
						case 'meh-o'  :  echo  '<span class=" fa fa-meh-o"></span>'; break;
						case 'mercury'  :  echo  '<span class=" fa fa-mercury"></span>'; break;
						case 'microphone'  :  echo  '<span class=" fa fa-microphone"></span>'; break;
						case 'microphone-slash'  :  echo  '<span class=" fa fa-microphone-slash"></span>'; break;
						case 'minus'  :  echo  '<span class=" fa fa-minus"></span>'; break;
						case 'minus-circle'  :  echo  '<span class=" fa fa-minus-circle"></span>'; break;
						case 'minus-square'  :  echo  '<span class=" fa fa-minus-square"></span>'; break;
						case 'minus-square-o'  :  echo  '<span class=" fa fa-minus-square-o"></span>'; break;
						case 'mobile'  :  echo  '<span class=" fa fa-mobile"></span>'; break;
						case 'money'  :  echo  '<span class=" fa fa-money"></span>'; break;
						case 'moon-o'  :  echo  '<span class=" fa fa-moon-o"></span>'; break;
						case 'motorcycle'  :  echo  '<span class=" fa fa-motorcycle"></span>'; break;
						case 'music'  :  echo  '<span class=" fa fa-music"></span>'; break;
						case 'neuter'  :  echo  '<span class=" fa fa-neuter"></span>'; break;
						case 'newspaper-o'  :  echo  '<span class=" fa fa-newspaper-o"></span>'; break;
						case 'openid'  :  echo  '<span class=" fa fa-openid"></span>'; break;
						case 'outdent'  :  echo  '<span class=" fa fa-outdent"></span>'; break;
						case 'pagelines'  :  echo  '<span class=" fa fa-pagelines"></span>'; break;
						case 'paint-brush'  :  echo  '<span class=" fa fa-paint-brush"></span>'; break;
						case 'paper-plane'  :  echo  '<span class=" fa fa-paper-plane"></span>'; break;
						case 'paper-plane-o'  :  echo  '<span class=" fa fa-paper-plane-o"></span>'; break;
						case 'paperclip'  :  echo  '<span class=" fa fa-paperclip"></span>'; break;
						case 'paragraph'  :  echo  '<span class=" fa fa-paragraph"></span>'; break;
						case 'pause'  :  echo  '<span class=" fa fa-pause"></span>'; break;
						case 'paw'  :  echo  '<span class=" fa fa-paw"></span>'; break;
						case 'paypal'  :  echo  '<span class=" fa fa-paypal"></span>'; break;
						case 'pencil'  :  echo  '<span class=" fa fa-pencil"></span>'; break;
						case 'pencil-square'  :  echo  '<span class=" fa fa-pencil-square"></span>'; break;
						case 'pencil-square-o'  :  echo  '<span class=" fa fa-pencil-square-o"></span>'; break;
						case 'phone'  :  echo  '<span class=" fa fa-phone"></span>'; break;
						case 'phone-square'  :  echo  '<span class=" fa fa-phone-square"></span>'; break;
						case 'picture-o'  :  echo  '<span class=" fa fa-picture-o"></span>'; break;
						case 'pie-chart'  :  echo  '<span class=" fa fa-pie-chart"></span>'; break;
						case 'pied-piper'  :  echo  '<span class=" fa fa-pied-piper"></span>'; break;
						case 'pied-piper-alt'  :  echo  '<span class=" fa fa-pied-piper-alt"></span>'; break;
						case 'pinterest'  :  echo  '<span class=" fa fa-pinterest"></span>'; break;
						case 'pinterest-p'  :  echo  '<span class=" fa fa-pinterest-p"></span>'; break;
						case 'pinterest-square'  :  echo  '<span class=" fa fa-pinterest-square"></span>'; break;
						case 'plane'  :  echo  '<span class=" fa fa-plane"></span>'; break;
						case 'play'  :  echo  '<span class=" fa fa-play"></span>'; break;
						case 'play-circle'  :  echo  '<span class=" fa fa-play-circle"></span>'; break;
						case 'play-circle-o'  :  echo  '<span class=" fa fa-play-circle-o"></span>'; break;
						case 'plug'  :  echo  '<span class=" fa fa-plug"></span>'; break;
						case 'plus'  :  echo  '<span class=" fa fa-plus"></span>'; break;
						case 'plus-circle'  :  echo  '<span class=" fa fa-plus-circle"></span>'; break;
						case 'plus-square'  :  echo  '<span class=" fa fa-plus-square"></span>'; break;
						case 'plus-square-o'  :  echo  '<span class=" fa fa-plus-square-o"></span>'; break;
						case 'power-off'  :  echo  '<span class=" fa fa-power-off"></span>'; break;
						case 'print'  :  echo  '<span class=" fa fa-print"></span>'; break;
						case 'puzzle-piece'  :  echo  '<span class=" fa fa-puzzle-piece"></span>'; break;
						case 'qq'  :  echo  '<span class=" fa fa-qq"></span>'; break;
						case 'qrcode'  :  echo  '<span class=" fa fa-qrcode"></span>'; break;
						case 'question'  :  echo  '<span class=" fa fa-question"></span>'; break;
						case 'question-circle'  :  echo  '<span class=" fa fa-question-circle"></span>'; break;
						case 'quote-left'  :  echo  '<span class=" fa fa-quote-left"></span>'; break;
						case 'quote-right'  :  echo  '<span class=" fa fa-quote-right"></span>'; break;
						case 'random'  :  echo  '<span class=" fa fa-random"></span>'; break;
						case 'rebel'  :  echo  '<span class=" fa fa-rebel"></span>'; break;
						case 'recycle'  :  echo  '<span class=" fa fa-recycle"></span>'; break;
						case 'reddit'  :  echo  '<span class=" fa fa-reddit"></span>'; break;
						case 'reddit-square'  :  echo  '<span class=" fa fa-reddit-square"></span>'; break;
						case 'refresh'  :  echo  '<span class=" fa fa-refresh"></span>'; break;
						case 'renren'  :  echo  '<span class=" fa fa-renren"></span>'; break;
						case 'repeat'  :  echo  '<span class=" fa fa-repeat"></span>'; break;
						case 'reply'  :  echo  '<span class=" fa fa-reply"></span>'; break;
						case 'reply-all'  :  echo  '<span class=" fa fa-reply-all"></span>'; break;
						case 'retweet'  :  echo  '<span class=" fa fa-retweet"></span>'; break;
						case 'road'  :  echo  '<span class=" fa fa-road"></span>'; break;
						case 'rocket'  :  echo  '<span class=" fa fa-rocket"></span>'; break;
						case 'rss'  :  echo  '<span class=" fa fa-rss"></span>'; break;
						case 'rss-square'  :  echo  '<span class=" fa fa-rss-square"></span>'; break;
						case 'rub'  :  echo  '<span class=" fa fa-rub"></span>'; break;
						case 'scissors'  :  echo  '<span class=" fa fa-scissors"></span>'; break;
						case 'search'  :  echo  '<span class=" fa fa-search"></span>'; break;
						case 'search-minus'  :  echo  '<span class=" fa fa-search-minus"></span>'; break;
						case 'search-plus'  :  echo  '<span class=" fa fa-search-plus"></span>'; break;
						case 'sellsy'  :  echo  '<span class=" fa fa-sellsy"></span>'; break;
						case 'server'  :  echo  '<span class=" fa fa-server"></span>'; break;
						case 'share'  :  echo  '<span class=" fa fa-share"></span>'; break;
						case 'share-alt'  :  echo  '<span class=" fa fa-share-alt"></span>'; break;
						case 'share-alt-square'  :  echo  '<span class=" fa fa-share-alt-square"></span>'; break;
						case 'share-square'  :  echo  '<span class=" fa fa-share-square"></span>'; break;
						case 'share-square-o'  :  echo  '<span class=" fa fa-share-square-o"></span>'; break;
						case 'shield'  :  echo  '<span class=" fa fa-shield"></span>'; break;
						case 'ship'  :  echo  '<span class=" fa fa-ship"></span>'; break;
						case 'shirtsinbulk'  :  echo  '<span class=" fa fa-shirtsinbulk"></span>'; break;
						case 'shopping-cart'  :  echo  '<span class=" fa fa-shopping-cart"></span>'; break;
						case 'sign-in'  :  echo  '<span class=" fa fa-sign-in"></span>'; break;
						case 'sign-out'  :  echo  '<span class=" fa fa-sign-out"></span>'; break;
						case 'signal'  :  echo  '<span class=" fa fa-signal"></span>'; break;
						case 'simplybuilt'  :  echo  '<span class=" fa fa-simplybuilt"></span>'; break;
						case 'sitemap'  :  echo  '<span class=" fa fa-sitemap"></span>'; break;
						case 'skyatlas'  :  echo  '<span class=" fa fa-skyatlas"></span>'; break;
						case 'skype'  :  echo  '<span class=" fa fa-skype"></span>'; break;
						case 'slack'  :  echo  '<span class=" fa fa-slack"></span>'; break;
						case 'sliders'  :  echo  '<span class=" fa fa-sliders"></span>'; break;
						case 'slideshare'  :  echo  '<span class=" fa fa-slideshare"></span>'; break;
						case 'smile-o'  :  echo  '<span class=" fa fa-smile-o"></span>'; break;
						case 'sort'  :  echo  '<span class=" fa fa-sort"></span>'; break;
						case 'sort-alpha-asc'  :  echo  '<span class=" fa fa-sort-alpha-asc"></span>'; break;
						case 'sort-alpha-desc'  :  echo  '<span class=" fa fa-sort-alpha-desc"></span>'; break;
						case 'sort-amount-asc'  :  echo  '<span class=" fa fa-sort-amount-asc"></span>'; break;
						case 'sort-amount-desc'  :  echo  '<span class=" fa fa-sort-amount-desc"></span>'; break;
						case 'sort-asc'  :  echo  '<span class=" fa fa-sort-asc"></span>'; break;
						case 'sort-desc'  :  echo  '<span class=" fa fa-sort-desc"></span>'; break;
						case 'sort-numeric-asc'  :  echo  '<span class=" fa fa-sort-numeric-asc"></span>'; break;
						case 'sort-numeric-desc'  :  echo  '<span class=" fa fa-sort-numeric-desc"></span>'; break;
						case 'soundcloud'  :  echo  '<span class=" fa fa-soundcloud"></span>'; break;
						case 'space-shuttle'  :  echo  '<span class=" fa fa-space-shuttle"></span>'; break;
						case 'spinner'  :  echo  '<span class=" fa fa-spinner"></span>'; break;
						case 'spoon'  :  echo  '<span class=" fa fa-spoon"></span>'; break;
						case 'spotify'  :  echo  '<span class=" fa fa-spotify"></span>'; break;
						case 'square'  :  echo  '<span class=" fa fa-square"></span>'; break;
						case 'square-o'  :  echo  '<span class=" fa fa-square-o"></span>'; break;
						case 'stack-exchange'  :  echo  '<span class=" fa fa-stack-exchange"></span>'; break;
						case 'stack-overflow'  :  echo  '<span class=" fa fa-stack-overflow"></span>'; break;
						case 'star'  :  echo  '<span class=" fa fa-star"></span>'; break;
						case 'star-half'  :  echo  '<span class=" fa fa-star-half"></span>'; break;
						case 'star-half-o'  :  echo  '<span class=" fa fa-star-half-o"></span>'; break;
						case 'star-o'  :  echo  '<span class=" fa fa-star-o"></span>'; break;
						case 'steam'  :  echo  '<span class=" fa fa-steam"></span>'; break;
						case 'steam-square'  :  echo  '<span class=" fa fa-steam-square"></span>'; break;
						case 'step-backward'  :  echo  '<span class=" fa fa-step-backward"></span>'; break;
						case 'step-forward'  :  echo  '<span class=" fa fa-step-forward"></span>'; break;
						case 'stethoscope'  :  echo  '<span class=" fa fa-stethoscope"></span>'; break;
						case 'stop'  :  echo  '<span class=" fa fa-stop"></span>'; break;
						case 'street-view'  :  echo  '<span class=" fa fa-street-view"></span>'; break;
						case 'strikethrough'  :  echo  '<span class=" fa fa-strikethrough"></span>'; break;
						case 'stumbleupon'  :  echo  '<span class=" fa fa-stumbleupon"></span>'; break;
						case 'stumbleupon-circle'  :  echo  '<span class=" fa fa-stumbleupon-circle"></span>'; break;
						case 'subscript'  :  echo  '<span class=" fa fa-subscript"></span>'; break;
						case 'subway'  :  echo  '<span class=" fa fa-subway"></span>'; break;
						case 'suitcase'  :  echo  '<span class=" fa fa-suitcase"></span>'; break;
						case 'sun-o'  :  echo  '<span class=" fa fa-sun-o"></span>'; break;
						case 'superscript'  :  echo  '<span class=" fa fa-superscript"></span>'; break;
						case 'table'  :  echo  '<span class=" fa fa-table"></span>'; break;
						case 'tablet'  :  echo  '<span class=" fa fa-tablet"></span>'; break;
						case 'tachometer'  :  echo  '<span class=" fa fa-tachometer"></span>'; break;
						case 'tag'  :  echo  '<span class=" fa fa-tag"></span>'; break;
						case 'tags'  :  echo  '<span class=" fa fa-tags"></span>'; break;
						case 'tasks'  :  echo  '<span class=" fa fa-tasks"></span>'; break;
						case 'taxi'  :  echo  '<span class=" fa fa-taxi"></span>'; break;
						case 'tencent-weibo'  :  echo  '<span class=" fa fa-tencent-weibo"></span>'; break;
						case 'terminal'  :  echo  '<span class=" fa fa-terminal"></span>'; break;
						case 'text-height'  :  echo  '<span class=" fa fa-text-height"></span>'; break;
						case 'text-width'  :  echo  '<span class=" fa fa-text-width"></span>'; break;
						case 'th'  :  echo  '<span class=" fa fa-th"></span>'; break;
						case 'th-large'  :  echo  '<span class=" fa fa-th-large"></span>'; break;
						case 'th-list'  :  echo  '<span class=" fa fa-th-list"></span>'; break;
						case 'thumb-tack'  :  echo  '<span class=" fa fa-thumb-tack"></span>'; break;
						case 'thumbs-down'  :  echo  '<span class=" fa fa-thumbs-down"></span>'; break;
						case 'thumbs-o-down'  :  echo  '<span class=" fa fa-thumbs-o-down"></span>'; break;
						case 'thumbs-o-up'  :  echo  '<span class=" fa fa-thumbs-o-up"></span>'; break;
						case 'thumbs-up'  :  echo  '<span class=" fa fa-thumbs-up"></span>'; break;
						case 'ticket'  :  echo  '<span class=" fa fa-ticket"></span>'; break;
						case 'times'  :  echo  '<span class=" fa fa-times"></span>'; break;
						case 'times-circle'  :  echo  '<span class=" fa fa-times-circle"></span>'; break;
						case 'times-circle-o'  :  echo  '<span class=" fa fa-times-circle-o"></span>'; break;
						case 'tint'  :  echo  '<span class=" fa fa-tint"></span>'; break;
						case 'toggle-off'  :  echo  '<span class=" fa fa-toggle-off"></span>'; break;
						case 'toggle-on'  :  echo  '<span class=" fa fa-toggle-on"></span>'; break;
						case 'train'  :  echo  '<span class=" fa fa-train"></span>'; break;
						case 'transgender'  :  echo  '<span class=" fa fa-transgender"></span>'; break;
						case 'transgender-alt'  :  echo  '<span class=" fa fa-transgender-alt"></span>'; break;
						case 'trash'  :  echo  '<span class=" fa fa-trash"></span>'; break;
						case 'trash-o'  :  echo  '<span class=" fa fa-trash-o"></span>'; break;
						case 'tree'  :  echo  '<span class=" fa fa-tree"></span>'; break;
						case 'trello'  :  echo  '<span class=" fa fa-trello"></span>'; break;
						case 'trophy'  :  echo  '<span class=" fa fa-trophy"></span>'; break;
						case 'truck'  :  echo  '<span class=" fa fa-truck"></span>'; break;
						case 'try'  :  echo  '<span class=" fa fa-try"></span>'; break;
						case 'tty'  :  echo  '<span class=" fa fa-tty"></span>'; break;
						case 'tumblr'  :  echo  '<span class=" fa fa-tumblr"></span>'; break;
						case 'tumblr-square'  :  echo  '<span class=" fa fa-tumblr-square"></span>'; break;
						case 'twitch'  :  echo  '<span class=" fa fa-twitch"></span>'; break;
						case 'twitter'  :  echo  '<span class=" fa fa-twitter"></span>'; break;
						case 'twitter-square'  :  echo  '<span class=" fa fa-twitter-square"></span>'; break;
						case 'umbrella'  :  echo  '<span class=" fa fa-umbrella"></span>'; break;
						case 'underline'  :  echo  '<span class=" fa fa-underline"></span>'; break;
						case 'undo'  :  echo  '<span class=" fa fa-undo"></span>'; break;
						case 'university'  :  echo  '<span class=" fa fa-university"></span>'; break;
						case 'unlock'  :  echo  '<span class=" fa fa-unlock"></span>'; break;
						case 'unlock-alt'  :  echo  '<span class=" fa fa-unlock-alt"></span>'; break;
						case 'upload'  :  echo  '<span class=" fa fa-upload"></span>'; break;
						case 'usd'  :  echo  '<span class=" fa fa-usd"></span>'; break;
						case 'user'  :  echo  '<span class=" fa fa-user"></span>'; break;
						case 'user-md'  :  echo  '<span class=" fa fa-user-md"></span>'; break;
						case 'user-plus'  :  echo  '<span class=" fa fa-user-plus"></span>'; break;
						case 'user-secret'  :  echo  '<span class=" fa fa-user-secret"></span>'; break;
						case 'user-times'  :  echo  '<span class=" fa fa-user-times"></span>'; break;
						case 'users'  :  echo  '<span class=" fa fa-users"></span>'; break;
						case 'venus'  :  echo  '<span class=" fa fa-venus"></span>'; break;
						case 'venus-double'  :  echo  '<span class=" fa fa-venus-double"></span>'; break;
						case 'venus-mars'  :  echo  '<span class=" fa fa-venus-mars"></span>'; break;
						case 'viacoin'  :  echo  '<span class=" fa fa-viacoin"></span>'; break;
						case 'video-camera'  :  echo  '<span class=" fa fa-video-camera"></span>'; break;
						case 'vimeo-square'  :  echo  '<span class=" fa fa-vimeo-square"></span>'; break;
						case 'vine'  :  echo  '<span class=" fa fa-vine"></span>'; break;
						case 'vk'  :  echo  '<span class=" fa fa-vk"></span>'; break;
						case 'volume-down'  :  echo  '<span class=" fa fa-volume-down"></span>'; break;
						case 'volume-off'  :  echo  '<span class=" fa fa-volume-off"></span>'; break;
						case 'volume-up'  :  echo  '<span class=" fa fa-volume-up"></span>'; break;
						case 'weibo'  :  echo  '<span class=" fa fa-weibo"></span>'; break;
						case 'weixin'  :  echo  '<span class=" fa fa-weixin"></span>'; break;
						case 'whatsapp'  :  echo  '<span class=" fa fa-whatsapp"></span>'; break;
						case 'wheelchair'  :  echo  '<span class=" fa fa-wheelchair"></span>'; break;
						case 'wifi'  :  echo  '<span class=" fa fa-wifi"></span>'; break;
						case 'windows'  :  echo  '<span class=" fa fa-windows"></span>'; break;
						case 'wordpress'  :  echo  '<span class=" fa fa-wordpress"></span>'; break;
						case 'wrench'  :  echo  '<span class=" fa fa-wrench"></span>'; break;
						case 'xing'  :  echo  '<span class=" fa fa-xing"></span>'; break;
						case 'xing-square'  :  echo  '<span class=" fa fa-xing-square"></span>'; break;
						case 'yahoo'  :  echo  '<span class=" fa fa-yahoo"></span>'; break;
						case 'yelp'  :  echo  '<span class=" fa fa-yelp"></span>'; break;
						case 'youtube'  :  echo  '<span class=" fa fa-youtube"></span>'; break;
						case 'youtube-play'  :  echo  '<span class=" fa fa-youtube-play"></span>'; break;
						case 'youtube-square'  :  echo  '<span class=" fa fa-youtube-square"></span>'; break;

                         }
            echo '</span><h2>'.strip_tags($title).'</h2>';
            echo   wpautop(do_shortcode(htmlspecialchars_decode('<p>'.$text.'</p>')));
            echo '</div>';
    }
}